# Generated by Django 4.0.2 on 2022-02-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='interview_schedule',
            old_name='CandidateName',
            new_name='CandidateNamee',
        ),
        migrations.RenameField(
            model_name='interview_schedule',
            old_name='interviewerName',
            new_name='interviewerNamee',
        ),
    ]
