# Generated by Django 4.0.2 on 2022-02-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0003_delete_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview_schedule',
            old_name='CandidateNamee',
            new_name='CandidateName',
        ),
        migrations.RenameField(
            model_name='interview_schedule',
            old_name='interviewerNamee',
            new_name='interviewerName',
        ),
    ]
